# Site settings
title: "Le 75e Régiment"
subtitle: "Équipe de jeu semi-milsim sur ArmA 3"
email: ""
author: ""
description: ""
url: ""
baseurl: ""
discordurl: "https://discord.gg/yBjRFQM4A8"

# Collections
collections:
  operations:

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
